# Generated by Django 4.2.5 on 2023-09-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0004_patient_email_alter_doctor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_idnum',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
