# Generated by Django 4.2.5 on 2023-09-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0005_patient_patient_idnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_idnum',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
