# Generated by Django 4.2.5 on 2023-09-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0008_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
